name: Build & Deploy Flutter Web

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./  # Use './flutter' if your Flutter project is inside a folder

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Install Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: 'stable'

    - name: Enable Flutter Web
      run: flutter config --enable-web

    - name: Install dependencies
      run: flutter pub get

    - name: Build Flutter Web
      run: flutter build web --release

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_branch: gh-pages
        publish_dir: build/web
