name: Build & Deploy Flutter Web

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.19.5"

      - name: Enable Flutter Web
        run: flutter config --enable-web
        working-directory: Dream.11

      - name: Install dependencies
        run: flutter pub get
        working-directory: Dream.11

      - name: Build web release
        run: flutter build web --release --base-href="/Dream.11/"
        working-directory: Dream.11

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: Dream.11/build/web
