name: Build & Deploy Flutter Web

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    defaults:
      run:
        # run all flutter commands inside the flutter/ folder
        working-directory: ./flutter

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Install Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.19.5'

    - name: Enable web support
      run: flutter config --enable-web

    - name: Get dependencies
      run: flutter pub get

    - name: Build web release
      run: flutter build web --release

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_branch: gh-pages
        # point to the web build inside flutter/
        publish_dir: flutter/build/web
